# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin

class LangRAG(BasePlugin):

    async def initialize(self) -> None:
        pass

    def __del__(self) -> None:
        pass
